# Generated by Django 4.0 on 2023-05-13 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('97e6d82b-0b0f-4e03-95ef-b33cabfd8aa9'), primary_key=True, serialize=False),
        ),
    ]
