# Generated by Django 4.0 on 2023-05-13 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('19e64726-8da3-4001-b9b7-8d50479b8616'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
