# Generated by Django 4.0 on 2023-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_meme_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
