# Generated by Django 4.0 on 2023-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_meme_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_text',
            field=models.CharField(max_length=500),
        ),
    ]
