# Generated by Django 4.0 on 2023-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_meme_meme_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_text',
            field=models.CharField(max_length=50000),
        ),
    ]
