# Generated by Django 4.0 on 2023-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_meme_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='raw_photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
